### ISSUE TITLE
Limited to 500 Chunks (8000 to -8000) world size?

### ISSUE THREAD

**Issue by K4N0** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#10]
It seems that no matter what I do, I can't seem to pregenerate to the world border of 10K to -10K. It's essentially a 20k x 20k world, but I can't seem to get that far with this mod. Am I doing something wrong or is that a limit to this mod?

**Comment by Speiger** [comment]
Limit is 500 chunk radius in 1 task, you can do multiple tasks to achieve that.
Or just upgrade.
[Pro Upgrade](https://github.com/TinyModularThings/Chunk-Pregenerator-Issue-Tracker/wiki/Pro-Version)
[Pro FAQ (or why it was done)](https://github.com/TinyModularThings/Chunk-Pregenerator-Issue-Tracker/wiki/Pro-Version-FAQ)
