### ISSUE TITLE
Problems generating the world

### ISSUE THREAD

**Issue by Lucas559-noob** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#11]
When I generate the world, I see that I start at night, and also most of trees that should exist on map don't exist, there is a fix for this?
Did this on 1.12.2

the only trees that exist are those that are very close to me, around 1, 2 chunks

**Comment by Speiger** [comment]
Please provide game logs.
Because with this info i can't really help you.
The game logs should contain your attempt to use it.

**Comment by Lucas559-noob** [comment]
from a lot of logs, this is the right I think, logs before were crashes, and this was the right after the post
[2022-12-18-6.log](https://github.com/TinyModularThings/Chunk-Pregenerator-Issue-Tracker/files/10280849/2022-12-18-6.log)

**Comment by Speiger** [comment]
@Lucas559-noob this log doesn't contain crashes, just you closing the game.
