### ISSUE TITLE
[1.19.2] Clicking "go back" in the "seed preview has moved to another mod" window goes back to main menu instead of world settings

### ISSUE THREAD

**Issue by Peca21** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#14]
When you click go back in the "seed preview has moved to another mod" window, minecraft returns back to main menu instead of the world settings screen that it was on.

**Comment by Speiger** [comment]
To keep the mod alive it has been moved to a "Supporter only" addon.
Due to curseforge i am not allowed to link to it directly. (Yes they specified it to me that way)
Here you find it.
https://github.com/TinyModularThings/Chunk-Pregenerator-Issue-Tracker/wiki/Pro-Version

**Comment by Speiger** [comment]
Dang forgot this one...
Doing that next patch.
