### ISSUE TITLE
Updated to new Forge forge-1.19.2-43.2.3 as Modpack ATM8 was updated and now get this error about Javafml:44

### ISSUE THREAD

**Issue by Possemaster** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#15]
[ERROR] forge-1.19.2-43.2.3-universal.jar |Forge |forge |43.2.3 |NONE |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df::0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90[07:49:45] [minecraft/Main]: Failed to start the minecraft server

net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [

Mod File Chunk+Pregenerator-1.19.3-4.2.0.jar needs language provider javafml:44 or above to load

**Comment by Possemaster** [comment]
Nevermind, I did not have my coffee yet. 1.19.2 vs 1.19.3. sorry for this.

**Comment by Speiger** [comment]
Love the self fixing bugs. xD
@Possemaster no worry. Glad that it wasn't a real issue :)
