### ISSUE TITLE
vague instructions and command lines

### ISSUE THREAD

**Issue by Freeeli** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#18]
instructions on how to generate prechunks are too vague

**Comment by Speiger** [comment]
@Freeeli I know, my todolist was just so great that I was not able to rewrite the documentation.
But it is on the todolist.

I am just 1 person working on a lot of projects that i am trying to finish at this point.
The rewrite of the docuemtation should happen this month (February)

**Comment by Freeeli** [comment]
my apologies mate keep up the good work

**Comment by Speiger** [comment]
@Freeeli that is totally fine ^^"
I know that this needs a rewrite badly.
And should have prioritized it a bit more then right now.

**Comment by Speiger** [comment]
@Freeeli documentation just got updated for 1.14 or newer.
1.12 is still valid but i will rewrite that at some point too, but that is a lot further away!
