### ISSUE TITLE
> > @+62 821-5354-4606

### ISSUE THREAD

**Issue by iqbalrezaamali** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#21]
> > @+62 821-5354-4606
S:recyclerBlacklist=minecraft:stick,minecraft:snowball,microblockcbe:microblock,microblockcbe:saw_stone,microblockcbe:saw_iron,microblockcbe:saw_diamond,projectred-exploration:golden_saw,projectred-exploration:ruby_saw,chiselsandbits:bitsaw_diamond,projectred-exploration:sapphire_saw,projectred-exploration:peridot_saw

_Originally posted by @iqbalrezaamali in https://github.com/TinyModularThings/IC2Classic/issues/678#issuecomment-1466413551_

**Comment by Speiger** [comment]
Wrong issue tracker.
