### ISSUE TITLE
Occultism compatibility issue

### ISSUE THREAD

**Issue by vojthus** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#23]
Minecraft version: 1.9.13
Forge version: 44.1.23

Chunk Pregen version: Chunk Pregenerator-1.19.3-4.2.2
Occultism: tested on 1.19.3-1.73.0 and 1.19.3-1.73.2

When both mods are active in a mod pack the Occult mod guidebook entries are missing icons:

How it looks:
![image](https://user-images.githubusercontent.com/53073547/228509922-607e4d79-51df-4b15-9bd6-9d8e2fdbc967.png)

How it should be:
![image](https://user-images.githubusercontent.com/53073547/228510031-eba2088a-336b-479e-907d-7d40225741ab.png)

I've spoken to the mod author, he can be reached here:
https://github.com/klikli-dev/modonomicon
https://discord.gg/trE4SHRXvb

**Comment by Speiger** [comment]
Thank you for reporting it.
I'll look into it the soon, at the moment developing new features and i want that to be done first :)
Should be hopefully addressed with the next patch!

**Comment by klikli-dev** [comment]
@Speiger that chest is a good point - I will look into that and check if it reproduces on my end, probably something overlooked when porting to 1.19.3. So disregard the chest for now, that is likely on me.

The vanishing icons seem a bit odd though - they are not reproducing on my side (without chunk pregenerator present).
First thing that comes to mind is that maybe you are rendering something in an event and the blitOffset or posestack is not reset correctly? I had similar issues with overlay rendering in occultism (which is very different from this scenario, but the posestack issue may still apply)

**Comment by klikli-dev** [comment]
@Speiger thanks a lot! I did not happen across it as seemingly most vanilla and other mod render code that does not disable depth testing has *other* render code before modonomicon's GUI is rendered that does disable it thus never causing the issue.

Only this one and ftb chunks seem to have the timing required to cause it. 

But that needs to be fixed on my end so you can close this :)

**Comment by Speiger** [comment]
@klikli-dev thanks :)
