### ISSUE TITLE
Shows as required on client when only server side loaded

### ISSUE THREAD

**Issue by celsiusqc** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#24]
![image](https://user-images.githubusercontent.com/63996164/228633288-cdcb1d5a-3e74-4d26-a50e-aaadbf4c57d3.png)

**Comment by celsiusqc** [comment]
It was, since its enabled by default I guess. I turned it off on the server config

**Comment by Speiger** [comment]
@celsiusqc it is only enabled by default if you load it up in singleplayer.
So moving configs from client to server will enable it by default :)

Welp not a bug. Intentional behavior :)
