### ISSUE TITLE
Remove Preview Button if double-dipped mod is not installed.

### ISSUE THREAD

**Issue by SephirothWS** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#29]
Thanks for removing the preview functionality from the mod and "moving it to another mod". I really love how mods are splitting into a bazillion separate jar files. I miss the good ol' days of SINGLE JARS for entire mods.

**Comment by SephirothWS** [comment]
> @SephirothWS This was done due to Curseforges request. 
> If i had a choice then I would have kept it a single mod.

Really now? This is the first time I've ever heard of this.

**Comment by Speiger** [comment]
@SephirothWS I know of a few mods that were asked to split mods or take them down otherwise already.
There is a reason why i am not telling WHERE it is.

Anyways closing the issue since this was just a question and it has been answered.
