### ISSUE TITLE
Server crashes on pregen

### ISSUE THREAD

**Issue by HollishKid** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#30]
I get the following crash report when pregenerating my world on a dedicated server :
https://pastebin.com/erijVSwQ

This task ran fine for a couple of hours, than it just crashed.
Can you recommand something I can do to prevent this from happening?

Thanks!

**Comment by Speiger** [comment]
@HollishKid o/
Looks like the [Ender Remaster mod](https://www.curseforge.com/minecraft/mc-mods/endremastered) could be at fault here.
Not really being able to handle multithreading properly
I am sorry but this isn't something I can fix. 
If you want you can link this issue report there and I will try to assist if possible.

**Comment by Speiger** [comment]
was fixed by the other dev
