### ISSUE TITLE
Area command confusion

### ISSUE THREAD

**Issue by redlive36** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#33]
Hey there, I must say that your mod has been working wonders for me in a modded environment. However, I have a question: how can I generate, for example, 700 blocks in front of me? I tried the /pregen start gen area command, and it says it's beyond the limit. Perhaps the expansion command could work aswell, but I can't find a way to reliably generate the terrain 600 blocks in front of me in the X coordinate. Here are some photos for clarification aswell. I apologize if I missed anything from the explanation videos, but I was hoping you could clear it up, as I have found no info for the area command. Thank you for your help and for reading this issue.
Images:
![2023-06-25_18 08 36](https://github.com/TinyModularThings/Chunk-Pregenerator-Issue-Tracker/assets/137713416/779dbbd9-5234-4bc9-a202-0d3613140572)
![2023-06-25_18 09 14](https://github.com/TinyModularThings/Chunk-Pregenerator-Issue-Tracker/assets/137713416/86971db7-5e4e-495e-875e-aaea5fe5c139)
![2023-06-25_18 09 18](https://github.com/TinyModularThings/Chunk-Pregenerator-Issue-Tracker/assets/137713416/9e992003-48b1-4813-8e14-17dfca16c47a)

**Comment by Meduris** [comment]
First of all, which minecraft version are you using?

Second, all values in the commands are in chunks, not blocks, so you need to divide the numbers by 16. Even then, it doesn't look like you used the correct arguments

**Comment by redlive36** [comment]
Thank you for your reply. I'm on 1.19.2. I will now try to do the same command with the chunk conversion to see if it works, thanks.

**Comment by Meduris** [comment]
for what you are trying to do, the command should be something like this:

``/pregen start gen radius gentest SQUARE ~600 ~ 18``

you don't need the dimension if you already are in that dimension. and the place where you had the two ~ is where you specify the center of the area that should be generated and after that comes the radius in a single number, not two

**Comment by redlive36** [comment]
Appreciate your response. I will try this now, thank you for the information.

**Comment by Speiger** [comment]
@redlive36 the "Area command" is not what you tried to do:
What you tried to do:
- X Start, Z Start, X width Z Width

What the area command is actually doing:
- X Start, Z Start, X End, Z End

So lets translate your command:
``/pregen start gen area TESTING SQUARE 13 143 217 2800``
Or to translate it into Blocks:
``/pregen start gen area TESTING SQUARE 208 2288 3472 44800``

So what you tried was basically a insanely big command that would have taken ages to complete.
Most likely a day or two.

The area command is basically ment to be specific areas that you know where to start from and end.
99% of the cases the radius command is enough.
EVEN IF YOU have it generate existing chunks, chunk pregen is fast enough to figure it out and take not even a second longer then if you would have placed the positions perfectly

**Comment by Meduris** [comment]
also I noticed a mistake with my radius command. ``~600`` shifts it by 600 chunks, so it should have rather been something like ``~38``

**Comment by redlive36** [comment]
Okay, thanks to both of you for helping me with this issue. The command Meduris provided was helpful and it generated the terrain I needed. So just in case, let's say I want to generate chunks to a point that is around 800 blocks from my direction, positive in the x axis. After dividing it by 16, the command for that would be /pregen start gen radius gentest SQUARE ~50 ~ 18, right? Again, apologies if I'm wrong, but I would really like to get this sorted out before moving to my survival world.

**Comment by Meduris** [comment]
> After dividing it by 16, the command for that would be /pregen start gen radius gentest SQUARE ~50 ~ 18, right?

sounds about right, yeah what this command generates is a 288 block radius though (or a 576x576 block square), so if you change the offset to 800 blocks, you most likely want to increase the radius too. Special case here is just, that considering it is a radius, if you want a 800x800 square, you'll take 800, divide it by 2 to get the radius and then divide it by 16 to get the radius in chunks

**Comment by redlive36** [comment]
Got it. Thank you so much, and have a great day :).
