### ISSUE TITLE
Commands not working and nothing in UI version 1.18.2 (modded)

### ISSUE THREAD

**Issue by GodProZEE** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#35]
There are no commands that are displaying for the mod and if I write an example command by copy pasting from the wiki, they don't work either. Plus, there is nothing in the UI.
![pregen1](https://github.com/TinyModularThings/Chunk-Pregenerator-Issue-Tracker/assets/100044640/0c7b13d5-5833-4d0b-9f8b-d4a8ec39da05)
![pregen2](https://github.com/TinyModularThings/Chunk-Pregenerator-Issue-Tracker/assets/100044640/1e3c5470-c55a-426e-b783-c76b520931c6)

**Comment by Speiger** [comment]
Do you have op permissions?
Or do you have cheats enabled?

**Comment by GodProZEE** [comment]
> Do you have op permissions? Or do you have cheats enabled?

Cheats are disabled and it's a singleplayer world, should I enable cheats for this?

**Comment by Speiger** [comment]
@GodProZEE you are required to have cheats enabled since this tool can max out your pc if ANYONE can use it at will

**Comment by Speiger** [comment]
Closing because the issue was: No cheats enabled.
I will include with the next version a command that will only be enabled if permissions are not provided.

**Comment by GodProZEE** [comment]
@Speiger Thank you very much! I couldn't find anywhere that cheats had to be enabled for this, sorry for wasting your time.

**Comment by Speiger** [comment]
@GodProZEE no worry, I could have provided this info ingame.
 And that is what i am planning on the next patch having a command that is only there if you dont have permissions and tell you you need have cheats/op rights to use this :) sooo this issue was good!

**Comment by GodProZEE** [comment]
@Speiger That's awesome! Have a good one!
