### ISSUE TITLE
Will Chunk Pregenerator work on a server with no players.

### ISSUE THREAD

**Issue by Kindredphoenix** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#37]
Can I start the generation and leave it to run and log off my server? Or do I need to be there while its running.

**Comment by Speiger** [comment]
Yes chunkpregen works without players.
In fact it even has config settings to pause if players log in.
And a warning message in the server selection screen (client side not required to see it) so you know if it is still running.
