### ISSUE TITLE
Version 1.16.5 can set "setPlayerLimit" ?

### ISSUE THREAD

**Issue by yota54123** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#40]
The problem I'm currently encountering is that when pregening, if there are players joining at that time, it will cause the server to lag. I would like to ask that Are there player limits like in version 1.12.2 ?

**Comment by Speiger** [comment]
It's a config setting.
And the config updates live

**Comment by yota54123** [comment]
> It's a config setting. And the config updates live

![image](https://github.com/TinyModularThings/Chunk-Pregenerator-Issue-Tracker/assets/80737911/1b5ed88b-76c4-472a-9d10-cdb458d55993)
ok this config @basic.cfg ?

**Comment by Speiger** [comment]
Yes
