### ISSUE TITLE
World not working after using it (1.19.4)

### ISSUE THREAD

**Issue by Blackninja04010** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#42]
I got the `Chunk Pregenerator-1.19.4-4.3.0` for my `Forge 1.19.4-45.2.0` I tried testing the mod by loading a minimum of 10 and a maximum of 100 (I'm not 100% sure if this is what it was, but i'm pretty sure it is) and after I ran the command I saw a widget pop up in the top left corner that showed the RAM and CPU usage (those are what I remember), but after a bit the widget disappeared, i then tried to open a chest but nothing happened, after waiting ~5 hours i thought it might be that i needed to reload my client (just forge with some mods), i loaded back in and the widget appeared again and disappeared again, so i relogged and when i tried loading back in it would stop loading in at 100% (i left it like this for ~9 hours and nothing happened), i can't get the world to load, i don't want to lose the 10-15 hours i spent on it, is there a fix for this or something?

**Comment by Blackninja04010** [comment]
It wasn't the CPU stats, it was the progress from the pregen task widget

**Comment by Speiger** [comment]
Please create a clip of you starting the pregenerator.

I want to see what you do.

**Comment by Blackninja04010** [comment]
@Speiger like screen record me using it? Any screen recorders that I've tried take a lot of CPU to use, that may cause problems

**Comment by Speiger** [comment]
@Blackninja04010 Its not about the CPU usage but its to see the behavior of whats happening so i can see exactly whats happening.
Otherwise its hard to help you.

**Comment by Blackninja04010** [comment]
@Speiger what screen recorder should I use?

**Comment by Speiger** [comment]
@Blackninja04010 anything that produces a watchable file.
ShareX/OBS/NvidiaReplay or any other that works. These three are just one of the most common ones i have seen.

**Comment by Speiger** [comment]
@Blackninja04010 is this still an issue?
