### ISSUE TITLE
Server Crashes Better Minecraft 4 1.20.1

### ISSUE THREAD

**Issue by Kina4You** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#45]
Hi,

I run a Better Minecraft server on the version  1.20.1 with my friend. We already played a bit and I just found this mod but it doesnt work for me. I added the mod to the server and my client and used the commands.
"/pregen start gen radius SQUARE Test 0 0 50 minecraft:overworld"
The pregen start but it crashes the server immediately. I also tried to not join the server and to use the command via console but it still crashes the server. The host ist "host-unlimited" and the server has 16GB Ram. 

I set the deletion to 1 to lower the CPU but it still didnt help. I tried it on the spawn which is already completely explored within 30 chunks and tried to generate again these 30 chunks but it didnt work.

Asking for help ^^ and thank you in advance

**Comment by Kina4You** [comment]
Tested it now in SingePlayer and it also crashes my game. Does Pregen even work with Better Minecraft?

**Comment by Speiger** [comment]
@Kina4You please provide a crashlog.
Also the example looks more like this: ``/pregen start gen radius GenExample SQUARE 0 0 100``
You have taskId/shape mixed up

**Comment by Kina4You** [comment]
My bad will provide you the log rn

**Comment by Kina4You** [comment]
Sry but I have to get up early and my server didnt start rn when i tried to add mod into the server mod folder. I will try to provide your the logs tomorrow when im back.

sry

**Comment by Kina4You** [comment]
[crash-2024-01-18_23.58.05-server.txt](https://github.com/TinyModularThings/Chunk-Pregenerator-Issue-Tracker/files/13991738/crash-2024-01-18_23.58.05-server.txt)

**Comment by Speiger** [comment]
@Kina4You its the lithium bug.
Simply disable the poi mixin or temporarily disable lithium.

**Comment by Kina4You** [comment]
How can I disable it. Sry i might be just stupid but can u explain it to me?
Is it in the config of the mod?

**Comment by jlp1528** [comment]
Add .disabled to the end of the file name. Make sure you have "view file extensions" turned on in Windows settings.

**Comment by Kina4You** [comment]
Where do i find the file? Is it in the mod folder or is it smth else?

**Comment by Speiger** [comment]
https://github.com/CaffeineMC/lithium-fabric/wiki/Configuration-File

**Comment by Kina4You** [comment]
Does it matter that we play on a Forge server?

**Comment by Speiger** [comment]
@Kina4You chunk pregen only supports forge servers.

**Comment by Kina4You** [comment]
Cant find Lithium in my server folder.

**Comment by Kina4You** [comment]
Is it possible for your to help me via discord?

**Comment by Speiger** [comment]
Lithium is a fabric mod.
But there are forge ports of it which have a different name :)

**Comment by Kina4You** [comment]
Ok.
But I cant find the mod which is a Lithium Port.
https://www.curseforge.com/minecraft/modpacks/better-mc-forge-bmc4
Could you download the modpack and find the problem?

**Comment by Speiger** [comment]
@Kina4You your lithium port is "radium"
