### ISSUE TITLE
Unable to use in singleplayer without commands

### ISSUE THREAD

**Issue by SouthernJohn** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#46]
I was attempting to use this mod to help generate some chunks to hopefully increase my performance. Cheats are disabled and I don't want to enable them and just use "the honor system". Is there a way I can access the /pregen commands without enabling cheats? I also have a couple of other mods that would be affected if I turned them on. Thanks!

**Comment by Speiger** [comment]
I am sorry but allowing it to run without cheats is simply a bad idea...

This is a really cpu straining task.
And allowing anyone to run it is simply not a good idea.

Even in Singleplayer.
And I can tell you even all alternatives require cheats to be enabled.

So I am sorry I can't help you.

**Comment by SouthernJohn** [comment]
No worries. I opened to LAN with cheats and did it that way then just
turned lan back off. Thank you.
