### ISSUE TITLE
crashing Direwolf20 1.20 pack version 1.12.0

### ISSUE THREAD

**Issue by jlp1528** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#47]
https://pste.ch/fefovaxeka.pl
Also has a tendency to throw the same crash on world reload.

**Comment by Speiger** [comment]
@jlp1528 the canery "Poi" optimization is the crash.
Simply disable that during pregeneration.

Chunk Pregen fixes a memory leak and  that kinda breaks lithium.
But neither lithium or Chunkpregen are at  fault. Its mojangs fault.

**Comment by jlp1528** [comment]
How to disable POI?

**Comment by Speiger** [comment]
https://github.com/AbdElAziz333/Canary/wiki/Configuration-File

**Comment by jlp1528** [comment]
Thank you! I thought this was a setting in the pregenerator, not canary
