### ISSUE TITLE
1.19.2 Crash during bookmark

### ISSUE THREAD

**Issue by RamuneNeptune** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#49]
Hi there server seems to crash eventually after running benchmark or generally any pre-gen that isn't really small, I believe given enough time it crashes

**Crash report:** https://mclo.gs/wpQYey0

1. Ran `/pregen start benchmark start`
2. Was fine for a couple minutes
3. Server crashed

- 1 player connected, myself
- Fairly modded 1.19.2 Forge server
- `Chunk Pregenerator-1.19-4.3.0.jar`

**Comment by Speiger** [comment]
Canery Poi optimization clashes with chunkpregen, due to a memory leak that chunkpregen fixes.
Simply turn of in canery the poi optimization or disable canery for a bit.
