### ISSUE TITLE
Mod and mod commands not being loaded in 1.19.2

### ISSUE THREAD

**Issue by dhasial** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#5]
I've been trying to get this to work with 1.19.2 using the Fabric mod loader (the modpack I'm using for this is [MedievalMC](https://github.com/LunaPixelStudios/Medieval-MC/wiki)) but there's no sign that it's even being loaded. Curseforge says that this ought to be compatible with 1.19.2, though the filename only specifies 1.19, so maybe it's not officially supported for slightly newer versions?

[Complete list of all installed mods](https://pastebin.com/7Y7wT1qM)
[Server logs](https://git.disroot.org/Overhead/pastes/raw/branch/main/MedivalMC_29%20Aug%202022%2004:42:48%20-0400.log)
Note that server logs had to be uploaded as a file to a git because for some reason pastebin's filters wouldn't let me upload it unless it was private, I don't know why.

**Comment by Speiger** [comment]
Yeah the problem is that this is a Forge mod. 

As the wiki FAQs first question also answers.

```
Question: Forge or Fabric?
Answer: This mod uses the Forge API, there is no Fabric Release done or planned at this moment, this might change later down the line if the Default API supports what I need.
```

**Comment by dhasial** [comment]
Ah I see, I missed that bit of the FAQ. Thanks for getting back to me.
