### ISSUE TITLE
Crash report for 1.20.1

### ISSUE THREAD

**Issue by nivthefox** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#51]
I was trying to debug some memory issues I was having and removed my entire modlist except bluemap and Chunk Pregenerator, and the server crashed within a few minutes of startup, with the attached crash report.  Haven't seen this before when using Chunk Pregen so I thought I'd report it incase it's useful!

[crash-2024-03-20_17.54.15-server.txt](https://github.com/TinyModularThings/Chunk-Pregenerator-Issue-Tracker/files/14670707/crash-2024-03-20_17.54.15-server.txt)

**Comment by Speiger** [comment]
@nivthefox that log doesn't contain anything that is chunkpregen related.
ChunkPregen doesn't do anything in the background unless you are using the pregenerator actively.

So very unlikely that this is an actual bug with chunkpregen

**Comment by nivthefox** [comment]
I was using ChunkPregenerator to do a worldgen at the time (10,000 block world border).  Sorry if that was unclear. I guess it's possible I just hit a random Minecraft core or Forge crash, but it was definitely during chunk generation by Pregenerator.

If you still think this is not ChunkPregen's problem, go ahead and close, though.  I don't have the world log any longer, but it was just spams of the Pregen status message right up until the stack trace.

**Comment by Speiger** [comment]
@nivthefox yeah i doubt this is chunkpregens fault because then i would have a lot more reports of this specific logs.
Most likely blue map does something that isn't expected.

Anyways. You can turn of the chat spam by simply run: /pregen info unlisten in the server console.
