### ISSUE TITLE
RAD2 Server Crash #2

### ISSUE THREAD

**Issue by duhneller** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#54]
Hello, I had submitted another issue where my server was crashing when doing a 100-chunk pregen and was able to fix that/successfully generate after removing the Lootr mod. However, now I tried to pregen a 500-chunk radius and received these two crash reports. Lootr mod was still removed. TIA!

[crash-2024-03-21_20.00.30-server.txt](https://github.com/TinyModularThings/Chunk-Pregenerator-Issue-Tracker/files/14723713/crash-2024-03-21_20.00.30-server.txt)
[crash-2024-03-21_20.08.58-server.txt](https://github.com/TinyModularThings/Chunk-Pregenerator-Issue-Tracker/files/14723714/crash-2024-03-21_20.08.58-server.txt)

**Comment by Speiger** [comment]
@duhneller you ran out of memory when the crash happend.
This is the reason.
