### ISSUE TITLE
TabbyChat's interface is completely broken

### ISSUE THREAD

**Issue by GedeonGrays** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#58]
Hello o/

**Minecraft Version:** 1.7.10
**Chunk-Pregenerator Version:** 4.4.5
**TabbyChat Version:** 1.11.2.2 (LiteLoader) / 1.12.2 (Forge) 

**Video report:** 

https://github.com/TinyModularThings/Chunk-Pregenerator-Issue-Tracker/assets/32182901/ed5ea3de-c5b1-461a-be23-2d710f154e28

If you type any characters into the chat, they are instantly deleted. Also, resizing chat does not work and there are no channels.
This problem appeared since Chunk-Pregenerator 4.4.2.

**Comment by Speiger** [comment]
@GedeonGrays there is a config option to replace the chat with modern chat in chunkpregenerator.
(I backported the command UI from 1.19.2 to 1.7.10)
Simply turn of in said config and it should be fine.

If that fixes it, then its not a bug.

**Comment by GedeonGrays** [comment]
> @GedeonGrays there is a config option to replace the chat with modern chat in chunkpregenerator. (I backported the command UI from 1.19.2 to 1.7.10) Simply turn of in said config and it should be fine.
> 
> If that fixes it, then its not a bug.

I just changed the parameter `disable-advanced-commandline=false` to **true**. But unfortunately, the problem remains😐

**Comment by Speiger** [comment]
@GedeonGrays interesting, does the same happen without the chat override mod?

**Comment by GedeonGrays** [comment]
> @GedeonGrays interesting, does the same happen without the chat override mod?

If you mean without TabbyChat, then everything works fine in that case.
