### ISSUE TITLE
NPEs when viewing World Data

### ISSUE THREAD

**Issue by GedeonGrays** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#59]
Hello o/

**Minecraft Version:** 1.7.10
**Chunk-Pregenerator Version:** 4.4.5
**Server Version:** any (pure Forge server too)

When trying to view some data in Server Data > World Data, an NPE occurs (and kicks from the server).

**Logs:**
Entities: https://pastebin.com/B5mC3Dik
Tiles: https://pastebin.com/C88E7wzN
Chunks: https://pastebin.com/f79YdPeR

**Comment by Speiger** [comment]
Already known, This will be addressed in the next patch.
It was discovered a week ago but i was already in the project that eats all my time.

**Comment by GedeonGrays** [comment]
> Already known, This will be addressed in the next patch. It was discovered a week ago but i was already in the project that eats all my time.

Yeah, I'm a little late with my report on these and other NPEs. Well, then I will wait for the next patch and update the reports🙃

**Comment by GedeonGrays** [comment]
Still happening with Chunk-Pregenerator 4.4.7 (only without Entities).
Tiles: https://pastebin.com/Mkq31QV1
Chunks: https://pastebin.com/6BWtWPdz

**Comment by Speiger** [comment]
@GedeonGrays thank you i will address that with the next patch.

**Comment by GedeonGrays** [comment]
Apparently fixed. I think we can close this issue if everything is completed.
