### ISSUE TITLE
[1.18.2] Server Crashes During Chunk Pregeneration with Lost Cities

### ISSUE THREAD

**Issue by ZeroThundr** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#6]
My server is crashing while pregenerating a 400-chunk radius. Started happening after I added a bunch of mods including Lost Cities, and Repurposed Structures.

[crash-2022-09-06_10.13.59-server.txt](https://github.com/TinyModularThings/Chunk-Pregenerator-Issue-Tracker/files/9495739/crash-2022-09-06_10.13.59-server.txt)

**Comment by Speiger** [comment]
Sorry, I missed this issue,
I will look into that at the end of the month when I am done with porting ic2c.

Thank you for the report.

**Comment by Speiger** [comment]
F i saw this and then went to sleep and forgot to do this...
So another patch

**Comment by Speiger** [comment]
@ZeroThundr sorry for the delay.
Just tested it, the latest build that will come out soon this is fixed.
