### ISSUE TITLE
1.12.2 get kicked for spamming

### ISSUE THREAD

**Issue by Sarocesch** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#64]
no matter if the mod is on the server or not as soon as i have it in i can no longer enter long messages 

after a certain length the connection is disconnected

very very nice and helpful mod hope this can be fixed quickly 

![image](https://github.com/TinyModularThings/Chunk-Pregenerator-Issue-Tracker/assets/91789564/63e84be7-d911-4606-bb3b-57d5ca61a72d)

**Comment by Speiger** [comment]
@Sarocesch that is actually a vanilla feature.
You can't send more than 1 message per second to minecrafts chat.
But chunkpregens messages are system messages not player messages.

Also could you send me the server log because otherwise i can't help you?

**Comment by Sarocesch** [comment]
The thing is I don't even send the message 

I enter more and more until I get kicked and it's because of the mod because it works without it and I don't have another one installed 


send the log immediately

**Comment by Sarocesch** [comment]
forgot to say I don't use a Forge but a Mohist server 
could also have to do with it so incompatible with the mod maybe 🤔

[client-latest.log](https://github.com/TinyModularThings/Chunk-Pregenerator-Issue-Tracker/files/15338608/client-latest.log)

[server-latest.log](https://github.com/TinyModularThings/Chunk-Pregenerator-Issue-Tracker/files/15338613/server-latest.log)

**Comment by Speiger** [comment]
@Sarocesch yeah i looked into it and the logs say nothing.

ChunkPregen technically only sends messages if you have have something running.

And I don't actively support custom server software.
So Mohist could be the problem here.

If there would have been something i could at least tried writing down a thing to patch but i am not doing blind investigations.

I am sorry ^^"

**Comment by Sarocesch** [comment]
mh all good, they can't help it either

it just happens whenever i go over a certain number when writing chat messages and also with commands when they reach a certain length 
I think it could be because of the tab complete function but it is very nice 

too bad but not to change 
thanks anyway

**Comment by Speiger** [comment]
@Sarocesch if it is the tab completion, then you simply turn it off in the configs.
Because i provided a way to disable it because if my thing breaks due to modincompat i want to provide a way to solve it.

**Comment by Sarocesch** [comment]
I mean this command preview 
have not found anything in the config 

![image](https://github.com/TinyModularThings/Chunk-Pregenerator-Issue-Tracker/assets/91789564/5f95dc28-2e21-4432-9ffa-29f518845035)

**Comment by Sarocesch** [comment]
not that I don't want the function

but it could be the kick reason

**Comment by Speiger** [comment]
@Sarocesch 
```
  # Disables the backport of the Command line from modern versions.
  # Which makes writing commands much easier
  B:disable-advanced-commandline=false
```

In the config file (base.cfg)

**Comment by Sarocesch** [comment]
I have set the value to True and it is still on 🤔

**Comment by Sarocesch** [comment]
so both values do nothing it always stays on have tested it on client and server always in `base.cfg`

**Comment by Speiger** [comment]
@Sarocesch that is a global setting. It requires a game restart after a change.

**Comment by Sarocesch** [comment]
I have restarted🤔

**Comment by Sarocesch** [comment]
it doesn't change anything not even in single player i don't understand it somehow 
I'm on the latest version with only the mod and have it set in the config and even if it's both values that always have the true

**Comment by Speiger** [comment]
@Sarocesch I will look into it next week.
This week other projects have a higher priority

**Comment by Sarocesch** [comment]
ok
Thanks

**Comment by Sarocesch** [comment]
Good day
Is there anything new

do not want to be annoying but is just relatively stupid the error

**Comment by Speiger** [comment]
@Sarocesch I have barely any time to work on the mod so it will take a while.
I have finished 1 out of 12 versions so far. 
The next 4 should go quickly but after that it will take a while...

**Comment by Sarocesch** [comment]
ok all good🧡
would be nice if you get in touch with me

**Comment by Speiger** [comment]
@Sarocesch i close the issue the moment the patch is out. So if you follow notifications of issues you should be fine.
