### ISSUE TITLE
BiomeTweaker support

### ISSUE THREAD

**Issue by ghost** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#65]
1.12.2, forge, mod version Chunk-Pregenerator-1.12.2-4.4.5.jar

I use the BiomeTweaker script, which is very important to me, which prevents the creation of world spawn in an inappropriate biome. Here it is:
```
badBiomes = forAllBiomesExcept("minecraft:forest","minecraft:birch_forest","minecraft:birch_forest_hills","minecraft:roofed_forest","minecraft:redwood_taiga","minecraft:redwood_taiga_hills","biomesoplenty:cherry_blossom_grove","biomesoplenty:grove","biomesoplenty:maple_woods","biomesoplenty:redwood_forest","biomesoplenty:seasonal_forest")
badBiomes.set("isSpawnBiome", false)
```
But if I create a world in pregen mode, then the world spawn can be in any biome. That is, the BiomeTweaker mod does not work with pregen.

**Comment by Speiger** [comment]
o/

Biome tweaker most likely needs an obscure way or a specific configuration to be loaded.

You will most likely need to create a world and use the pregen command instead.

Not sure if that is fixable unless biome tweaker is still supported on 1.12.2

**Comment by ghost** [comment]
I thought of doing this - immediately after creating the world, enter a command using the Default World Generator mod. However, in this case the game will run VERY slowly for several minutes. I installed Chunk Pregenerator for one reason - after creating a world, TPS drops very much, and this continues for about 1 minute. If the player plays, he will be annoyed and disappointed. If he waits, then the world will work on its own, and I don’t want that. Is it possible to forcefully pause the game until pregeneration finishes? So that new chunks are generated, but no processes, calculations, changes or AI behavior occur.

**Comment by Speiger** [comment]
@somebush
That is sadly impossible.
Even when you use the preview it will simulate the world exactly like it would happen normally.
The player simply is not logged into the world instead.

It is like if you setup a dedicated server and run a pregeneration on that.
What you could do is set yourself into creative & peaceful run the pregen command and then reset the time & out of creative after the fact.
Or pregen the world using a dedicated server.

**Comment by ghost** [comment]
I started the pregeneration of quite a large number of chunks. After that I entered the world. The mod that displays the current time showed me that it is morning. There were also no signs that the mobs were moving or doing anything.
