### ISSUE TITLE
1.12.2 not running

### ISSUE THREAD

**Issue by Sebz102030** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#67]
after adding [Phosphor](https://www.curseforge.com/minecraft/mc-mods/phosphor-forge) mod started throwing messege below
![obraz_2024-05-26_160237281](https://github.com/TinyModularThings/Chunk-Pregenerator-Issue-Tracker/assets/101899869/3367fba0-25e9-45ee-9d96-f6bb628281e9)

modlist
![image](https://github.com/TinyModularThings/Chunk-Pregenerator-Issue-Tracker/assets/101899869/a9c2b523-c7f8-4a9f-a0ea-2dc9c95866d3)
![image](https://github.com/TinyModularThings/Chunk-Pregenerator-Issue-Tracker/assets/101899869/3b773335-945c-48ef-bd7f-38d96588684e)

**Comment by Speiger** [comment]
@Sebz102030 that is due to the chunks being generated.
Or is this a freshly created world?

**Comment by Sebz102030** [comment]
Chunk earlyer bee generated but after adding mod meshoned There is only comment about ending the process of generating chunks

**Comment by Sebz102030** [comment]
Another thing is that it is on Arm on raspberry pi 4

**Comment by Speiger** [comment]
@Sebz102030 the Prepare process is basically scanning if chunks have been generated.
And if that is true it will remove it of the queue.
So the pregenerator deemed all chunks to be pregenerated.

**Comment by Sebz102030** [comment]
So you are seing that this chunk are generated after starting server right?

**Comment by Meduris** [comment]
the generated chunks are saved to the savefile, same as when a player explores and chunks are generated where the player goes.

So if you rerun the same pregen command again and again, it won't magically generate new chunks, as the ones you tell it to generate are already there

**Comment by Sebz102030** [comment]
So it is how it supoutu be
