### ISSUE TITLE
Forward slash only opens up text without a / at the start

### ISSUE THREAD

**Issue by Oregano1963** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#68]
When trying to type a command, I have to write / twice as it won't open with one at the start.

Happens with just chunk pregen on forge.

**Comment by Speiger** [comment]
Duplicate

**Comment by Oregano1963** [comment]
I should've mentioned: it's the 1.12 version of the mod, not just the 1.7 version

**Comment by Speiger** [comment]
@Oregano1963 this is an issue between 1.7.10 -> 1.12.2 but 1 report is enough.
Usually if something is reported a patch if needed will but auto applied to all supported mc versions
