### ISSUE TITLE
1.12.2 Can't "rejoin" Undefined message for discriminator 0 in channel chunkpregenerator

### ISSUE THREAD

**Issue by HawkAngel** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#69]
[error2.txt](https://github.com/user-attachments/files/15527323/error2.txt)
PC that wants to join was been pregenning a world. I paused the pregen to try and join this server. First time I got in fine...was messing with startup flags for a bit and now am no longer able to rejoin it with that error being thrown. I tried going back to the startup flags for the server that worked the first time, and restarted both the client and server and no luck.

Can provide full logs from from the server if needed...assumed those were the only relevant parts.

**Comment by Speiger** [comment]
@HawkAngel this looks like the server and client have mismatching versions.

Please make sure that either the versions match between server and client or that the client doesn't have the mod installed.

**Comment by HawkAngel** [comment]
@Speiger Uninstalling the mod from the client works for joining....turns out RLCraft is still using the 2.5.1.jar version and the server I assumed it was newest and grabbed that version thanks(which also works as well)!
