### ISSUE TITLE
1.12.2 cant/doesn't pause when Player Limit is set

### ISSUE THREAD

**Issue by HawkAngel** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#70]
/pregen utils setPlayerLimit 1
This is the older version that no longer works....

Found that Player Limit needs to be set in a config...however I can't find a config file.

I then OP my player and tried to change the settings there to Player Limit 1...however the pregenerator still ran when that was done.
(Tried running cmds from the player and from the server, no difference)

**Comment by Speiger** [comment]
@HawkAngel please make sure you are using the right config file.
Because the config file was changed to the name "pregen/base.cfg"
