### ISSUE TITLE
[1.12] World creation crash

### ISSUE THREAD

**Issue by Sereath** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#72]
On a clean instance with only Chunk-Pregenerator and Carbon Config:

https://gist.github.com/Sereath/bf21855740fa55022abd3efb330c1434

**Comment by Speiger** [comment]
Ok, will address this tomorrow.

**Comment by Lodgercat** [comment]
Can confirm it's also an issue with joining a pre-existing multiplayer world I'm hosting after updating to the latest version

https://mclo.gs/boBcWio

**Comment by Speiger** [comment]
@Lodgercat @Sereath Fixed
