### ISSUE TITLE
Update the documentation

### ISSUE THREAD

**Issue by mpwhitacre** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#73]
It looks like in recent versions the command syntax has slightly changed. I am using the version for 1.20.1 and I cannot guarantee that the commands are working the same as described in the documents. I would recommend updating the read me to cover the new command syntax or adding help commands into the mod itself.

**Comment by Meduris** [comment]
anything newer then 1.12 always used the commands as documented here in the github wiki: https://github.com/TinyModularThings/Chunk-Pregenerator-Issue-Tracker/wiki

and with ~recent versions older versions~ recent updates, older mc versions were migrated to the same command system as the newer versions always used

**Comment by Meduris** [comment]
or more specific: https://github.com/TinyModularThings/Chunk-Pregenerator-Issue-Tracker/wiki/Commands

**Comment by Speiger** [comment]
@mpwhitacre the documentation is accurate between 1.7.10->1.20.6
