### ISSUE TITLE
Updated it and crash the game now on 1.12.2

### ISSUE THREAD

**Issue by Lucas559-noob** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#76]
[crash-2024-07-07_21.29.56-client.txt](https://github.com/user-attachments/files/16121534/crash-2024-07-07_21.29.56-client.txt)

**Comment by HattMudson** [comment]
can confirm - everything beyond Chunk-Pregenerator-1.12.2-4.4.5.jar crashes my fresh Divine Journey 2 (1.12.2) server

[crash-2024-07-13_11.18.23-server.txt](https://github.com/user-attachments/files/16249244/crash-2024-07-13_11.18.23-server.txt)
[crash-2024-07-15_16.48.40-server.txt](https://github.com/user-attachments/files/16249242/crash-2024-07-15_16.48.40-server.txt)
[crash-2024-07-14_02.59.02-server.txt](https://github.com/user-attachments/files/16249243/crash-2024-07-14_02.59.02-server.txt)
[crash-2024-07-16_14.01.32-server.txt](https://github.com/user-attachments/files/16249239/crash-2024-07-16_14.01.32-server.txt)
[crash-2024-07-16_13.56.55-server.txt](https://github.com/user-attachments/files/16249240/crash-2024-07-16_13.56.55-server.txt)
[crash-2024-07-15_16.50.29-server.txt](https://github.com/user-attachments/files/16249241/crash-2024-07-15_16.50.29-server.txt)

note: Chunk Pregenerator-V1.12-2.5.7.jar didn't crash but lost nbt data resulting in dungeons with pig spawners and unusable chests

**Comment by chilletize** [comment]
> can confirm - everything beyond Chunk-Pregenerator-1.12.2-4.4.5.jar crashes my fresh Divine Journey 2 (1.12.2) server
> 
> [crash-2024-07-13_11.18.23-server.txt](https://github.com/user-attachments/files/16249244/crash-2024-07-13_11.18.23-server.txt) [crash-2024-07-15_16.48.40-server.txt](https://github.com/user-attachments/files/16249242/crash-2024-07-15_16.48.40-server.txt) [crash-2024-07-14_02.59.02-server.txt](https://github.com/user-attachments/files/16249243/crash-2024-07-14_02.59.02-server.txt) [crash-2024-07-16_14.01.32-server.txt](https://github.com/user-attachments/files/16249239/crash-2024-07-16_14.01.32-server.txt) [crash-2024-07-16_13.56.55-server.txt](https://github.com/user-attachments/files/16249240/crash-2024-07-16_13.56.55-server.txt) [crash-2024-07-15_16.50.29-server.txt](https://github.com/user-attachments/files/16249241/crash-2024-07-15_16.50.29-server.txt)
> 
> note: Chunk Pregenerator-V1.12-2.5.7.jar didn't crash but lost nbt data resulting in dungeons with pig spawners and unusable chests

You don't have CarbonConfig installed, it's a requirement and it crashes due to not finding it.

**Comment by Speiger** [comment]
This requirement was added in the latest version
