### ISSUE TITLE
ingame ui not showing any options - minecraft 1.18.2 - forge 40.1.80

### ISSUE THREAD

**Issue by wwwdotfriend** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#8]
i might be a bit blind, but i've looked through the entire wiki and couldn't find a fix.

the ui only shows the "Disable PregenUI" button, which does nothing on click. this happens both in single player and my modded server.

**Comment by Speiger** [comment]
@wwwdotfriend moved to another mod.
[Link](https://github.com/TinyModularThings/Chunk-Pregenerator-Issue-Tracker/wiki/Pro-Version)
