### ISSUE TITLE
Not working with 1.21.1 NEOFORGE

### ISSUE THREAD

**Issue by GregX0** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#88]
Hi, the mod crashes the server when I switched from 1.21 to 1.21.1 NEOFORGE. Could you update the Mod?

**Comment by Meduris** [comment]
Which file did you use? Chunk pregen and carbon config both have separate downloads for neoforge which both have neoforge in the filenames.

Apart from that, if it crashes post a crashlog, otherwise we can't help you even if this is a legit crash

**Comment by GregX0** [comment]
I didn't notice the dependency on carbon config, it might have been in the modpack before. I will test it with adding it, if it works I will close, else send the crash report

**Comment by GregX0** [comment]
It was just the missing dependency, I found now it have been removed in that pack. thats why, thank you. I close it
