### ISSUE TITLE
Chunk-Pregenerator crashing at startup

### ISSUE THREAD

**Issue by RainGamma** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#90]
For some reason Chunk-Pregenerator crashes the server at startup, I can't figure out why from the crash file.

[crash-2024-11-03_15.51.05-fml.txt](https://github.com/user-attachments/files/17612263/crash-2024-11-03_15.51.05-fml.txt)

**Comment by RainGamma** [comment]
Server is version 1.20.1 and I was using chunk-pregen version 4.4.4

**Comment by Speiger** [comment]
@RainGamma missing carbon config dependency.
Which is advertised on Curseforge Too.

**Comment by Meduris** [comment]
https://www.curseforge.com/minecraft/mc-mods/carbon-config

**Comment by RainGamma** [comment]
Oh thanks im blind
