### ISSUE TITLE
Server crashes on startup on 1.7.10 GT:New Horizons

### ISSUE THREAD

**Issue by Wickdphreak** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#91]
I think I should have the right versions of both Chunk-Pregenerator and Carbonconfig, but server just keeps crashing on startup. Some help would be greatly appreciated! :))

[crash-2024-11-04_01.33.00-server.txt](https://github.com/user-attachments/files/17613012/crash-2024-11-04_01.33.00-server.txt)

**Comment by Speiger** [comment]
Update archaic fix
